#!/usr/bin/python

from os import system 

script = os.path.realpath (os.path.dirname (__file__))

command_block = '''
sudo pip install colorama && sudo pip install paramiko
sudo mv "''' + script + '''/brutos" /usr/bin
sudo chmod +x /usr/bin/brutos
sudo mv "''' + script + '''/brutos_files" /usr/bin
'''

system (command_block)

print 'Installed!'
